"""Seed alpha library — DSL formula strings the engine can evaluate.

A mix of WorldQuant "101 Formulaic Alphas" (Kakushadze 2015, arXiv:1601.00991)
transcribed into our DSL, plus classic academic factor signals. Each is validated
at import-time-adjacent (see validate_seeds.py); only parseable, non-degenerate
formulas are used. `family` groups them for diversification + the UI.
"""

SEEDS = [
    # ---------------- WorldQuant Alpha101 (transcribed) ----------------
    dict(name="alpha001", family="reversal",
         formula="rank(ts_argmax(signedpower(iif(returns < 0, stddev(returns, 20), close), 2.0), 5)) - 0.5"),
    dict(name="alpha002", family="volume",
         formula="-1 * correlation(rank(delta(log(volume), 2)), rank((close - open) / open), 6)"),
    dict(name="alpha003", family="volume",
         formula="-1 * correlation(rank(open), rank(volume), 10)"),
    dict(name="alpha004", family="reversal",
         formula="-1 * ts_rank(rank(low), 9)"),
    dict(name="alpha005", family="value",
         formula="rank(open - (ts_sum(vwap, 10) / 10)) * (-1 * abs(rank(close - vwap)))"),
    dict(name="alpha006", family="volume",
         formula="-1 * correlation(open, volume, 10)"),
    dict(name="alpha007", family="volume",
         formula="iif(adv(20) < volume, -1 * ts_rank(abs(delta(close, 7)), 60) * sign(delta(close, 7)), -1)"),
    dict(name="alpha008", family="momentum",
         formula="-1 * rank((ts_sum(open, 5) * ts_sum(returns, 5)) - delay(ts_sum(open, 5) * ts_sum(returns, 5), 10))"),
    dict(name="alpha009", family="momentum",
         formula="iif(ts_min(delta(close, 1), 5) > 0, delta(close, 1), iif(ts_max(delta(close, 1), 5) < 0, delta(close, 1), -1 * delta(close, 1)))"),
    dict(name="alpha010", family="momentum",
         formula="rank(iif(ts_min(delta(close, 1), 4) > 0, delta(close, 1), iif(ts_max(delta(close, 1), 4) < 0, delta(close, 1), -1 * delta(close, 1))))"),
    dict(name="alpha012", family="reversal",
         formula="sign(delta(volume, 1)) * (-1 * delta(close, 1))"),
    dict(name="alpha013", family="volume",
         formula="-1 * rank(covariance(rank(close), rank(volume), 5))"),
    dict(name="alpha014", family="volume",
         formula="(-1 * rank(delta(returns, 3))) * correlation(open, volume, 10)"),
    dict(name="alpha015", family="volume",
         formula="-1 * ts_sum(rank(correlation(rank(high), rank(volume), 3)), 3)"),
    dict(name="alpha016", family="volume",
         formula="-1 * rank(covariance(rank(high), rank(volume), 5))"),
    dict(name="alpha017", family="reversal",
         formula="((-1 * rank(ts_rank(close, 10))) * rank(delta(delta(close, 1), 1))) * rank(ts_rank(volume / adv(20), 5))"),
    dict(name="alpha018", family="reversal",
         formula="-1 * rank((stddev(abs(close - open), 5) + (close - open)) + correlation(close, open, 10))"),
    dict(name="alpha019", family="momentum",
         formula="(-1 * sign((close - delay(close, 7)) + delta(close, 7))) * (1 + rank(1 + ts_sum(returns, 250)))"),
    dict(name="alpha020", family="reversal",
         formula="((-1 * rank(open - delay(high, 1))) * rank(open - delay(close, 1))) * rank(open - delay(low, 1))"),
    dict(name="alpha022", family="volume",
         formula="-1 * (delta(correlation(high, volume, 5), 5) * rank(stddev(close, 20)))"),
    dict(name="alpha023", family="reversal",
         formula="iif((ts_sum(high, 20) / 20) < high, -1 * delta(high, 2), 0)"),
    dict(name="alpha024", family="momentum",
         formula="iif(delta(ts_sum(close, 100) / 100, 100) / delay(close, 100) <= 0.05, -1 * (close - ts_min(close, 100)), -1 * delta(close, 3))"),
    dict(name="alpha025", family="value",
         formula="rank(((-1 * returns) * adv(20)) * vwap * (high - close))"),
    dict(name="alpha026", family="volume",
         formula="-1 * ts_max(correlation(ts_rank(volume, 5), ts_rank(high, 5), 5), 3)"),
    dict(name="alpha028", family="volume",
         formula="scale((correlation(adv(20), low, 5) + ((high + low) / 2)) - close)"),
    dict(name="alpha032", family="value",
         formula="scale((ts_sum(close, 7) / 7) - close) + (20 * scale(correlation(vwap, delay(close, 5), 230)))"),
    dict(name="alpha033", family="value",
         formula="rank(-1 * (1 - (open / close)))"),
    dict(name="alpha034", family="volatility",
         formula="rank((1 - rank(stddev(returns, 2) / stddev(returns, 5))) + (1 - rank(delta(close, 1))))"),
    dict(name="alpha035", family="volume",
         formula="ts_rank(volume, 32) * (1 - ts_rank((close + high) - low, 16)) * (1 - ts_rank(returns, 32))"),
    dict(name="alpha037", family="value",
         formula="rank(correlation(delay(open - close, 1), close, 200)) + rank(open - close)"),
    dict(name="alpha038", family="reversal",
         formula="(-1 * rank(ts_rank(close, 10))) * rank(close / open)"),
    dict(name="alpha040", family="volatility",
         formula="(-1 * rank(stddev(high, 10))) * correlation(high, volume, 10)"),
    dict(name="alpha041", family="value",
         formula="((high * low) ** 0.5) - vwap"),
    dict(name="alpha042", family="value",
         formula="rank(vwap - close) / rank(vwap + close)"),
    dict(name="alpha043", family="reversal",
         formula="ts_rank(volume / adv(20), 20) * ts_rank(-1 * delta(close, 7), 8)"),
    dict(name="alpha044", family="volume",
         formula="-1 * correlation(high, rank(volume), 5)"),
    dict(name="alpha045", family="momentum",
         formula="-1 * (rank(ts_sum(delay(close, 5), 20) / 20) * correlation(close, volume, 2) * rank(correlation(ts_sum(close, 5), ts_sum(close, 20), 2)))"),
    dict(name="alpha046", family="momentum",
         formula="iif((delay(close, 20) - delay(close, 10)) / 10 - (delay(close, 10) - close) / 10 > 0.25, -1, iif((delay(close, 20) - delay(close, 10)) / 10 - (delay(close, 10) - close) / 10 < 0, 1, -1 * (close - delay(close, 1))))"),
    dict(name="alpha049", family="momentum",
         formula="iif((delay(close, 20) - delay(close, 10)) / 10 - (delay(close, 10) - close) / 10 < -0.1, 1, -1 * (close - delay(close, 1)))"),
    dict(name="alpha051", family="momentum",
         formula="iif((delay(close, 20) - delay(close, 10)) / 10 - (delay(close, 10) - close) / 10 < -0.05, 1, -1 * (close - delay(close, 1)))"),
    dict(name="alpha052", family="momentum",
         formula="((-1 * ts_min(low, 5)) + delay(ts_min(low, 5), 5)) * rank((ts_sum(returns, 240) - ts_sum(returns, 20)) / 220) * ts_rank(volume, 5)"),
    dict(name="alpha053", family="reversal",
         formula="-1 * delta(((close - low) - (high - close)) / (close - low), 9)"),
    dict(name="alpha054", family="value",
         formula="(-1 * ((low - close) * (open ** 5))) / ((low - high) * (close ** 5))"),
    dict(name="alpha055", family="reversal",
         formula="-1 * correlation(rank((close - ts_min(low, 12)) / (ts_max(high, 12) - ts_min(low, 12))), rank(volume), 6)"),
    dict(name="alpha060", family="volume",
         formula="-1 * ((2 * scale(rank((((close - low) - (high - close)) / (high - low)) * volume))) - scale(rank(ts_argmax(close, 10))))"),
    dict(name="alpha061", family="value",
         formula="rank(vwap - ts_min(vwap, 16)) < rank(correlation(vwap, adv(180), 18))"),
    dict(name="alpha065", family="value",
         formula="rank(correlation((open * 0.0097) + (vwap * 0.99), ts_sum(adv(60), 9), 6)) < rank(open - ts_min(open, 14))"),
    dict(name="alpha068", family="volume",
         formula="ts_rank(correlation(rank(high), rank(adv(15)), 9), 14) < rank(delta((close * 0.518) + (low * 0.482), 1))"),
    dict(name="alpha071", family="value",
         formula="maximum(ts_rank(decay_linear(correlation(ts_rank(close, 3), ts_rank(adv(180), 12), 18), 4), 16), ts_rank(decay_linear(rank((low + open) - (vwap + vwap)) ** 2, 16), 4))"),
    dict(name="alpha072", family="volume",
         formula="rank(decay_linear(correlation((high + low) / 2, adv(40), 9), 10)) / rank(decay_linear(correlation(ts_rank(vwap, 4), ts_rank(volume, 19), 7), 3))"),
    dict(name="alpha073", family="value",
         formula="-1 * maximum(rank(decay_linear(delta(vwap, 5), 3)), ts_rank(decay_linear((delta((open * 0.147) + (low * 0.853), 2) / ((open * 0.147) + (low * 0.853))) * -1, 3), 17))"),
    dict(name="alpha074", family="volume",
         formula="rank(correlation(close, ts_sum(adv(30), 37), 15)) < rank(correlation(rank((high * 0.026) + (vwap * 0.974)), rank(volume), 11))"),
    dict(name="alpha075", family="volume",
         formula="rank(correlation(vwap, volume, 4)) < rank(correlation(rank(low), rank(adv(50)), 12))"),
    dict(name="alpha077", family="value",
         formula="minimum(rank(decay_linear(((high + low) / 2) + high - (vwap + high), 20)), rank(decay_linear(correlation((high + low) / 2, adv(40), 3), 6)))"),
    dict(name="alpha078", family="volume",
         formula="rank(correlation(ts_sum((low * 0.352) + (vwap * 0.648), 20), ts_sum(adv(40), 20), 7)) ** rank(correlation(rank(vwap), rank(volume), 6))"),
    dict(name="alpha081", family="volume",
         formula="-1 * (rank(log(product(rank(rank(correlation(vwap, ts_sum(adv(10), 50), 8)) ** 4), 15))) < rank(correlation(rank(vwap), rank(volume), 5)))"),
    dict(name="alpha083", family="value",
         formula="(rank(delay((high - low) / (ts_sum(close, 5) / 5), 2)) * rank(rank(volume))) / (((high - low) / (ts_sum(close, 5) / 5)) / (vwap - close))"),
    dict(name="alpha084", family="value",
         formula="signedpower(ts_rank(vwap - ts_max(vwap, 15), 21), delta(close, 5))"),
    dict(name="alpha085", family="volume",
         formula="rank(correlation((high * 0.877) + (close * 0.123), adv(30), 10)) ** rank(correlation(ts_rank((high + low) / 2, 4), ts_rank(volume, 10), 7))"),
    dict(name="alpha086", family="value",
         formula="-1 * (ts_rank(correlation(close, ts_sum(adv(20), 15), 6), 20) < rank((open + close) - (vwap + open)))"),
    dict(name="alpha088", family="volume",
         formula="minimum(rank(decay_linear((rank(open) + rank(low)) - (rank(high) + rank(close)), 8)), ts_rank(decay_linear(correlation(ts_rank(close, 8), ts_rank(adv(60), 21), 8), 7), 3))"),
    dict(name="alpha092", family="volume",
         formula="minimum(ts_rank(decay_linear(iif(((high + low) / 2) + close < (low + open), 1, 0), 15), 19), ts_rank(decay_linear(correlation(rank(low), rank(adv(30)), 8), 7), 7))"),
    dict(name="alpha094", family="value",
         formula="-1 * (rank(vwap - ts_min(vwap, 12)) ** ts_rank(correlation(ts_rank(vwap, 20), ts_rank(adv(60), 4), 18), 3))"),
    dict(name="alpha095", family="volume",
         formula="rank(open - ts_min(open, 12)) < ts_rank(rank(correlation(ts_sum((high + low) / 2, 19), ts_sum(adv(40), 19), 13)) ** 5, 12)"),
    dict(name="alpha096", family="volume",
         formula="-1 * maximum(ts_rank(decay_linear(correlation(rank(vwap), rank(volume), 4), 4), 8), ts_rank(decay_linear(ts_argmax(correlation(ts_rank(close, 7), ts_rank(adv(60), 4), 4), 13), 14), 13))"),
    dict(name="alpha098", family="volume",
         formula="rank(decay_linear(correlation(vwap, ts_sum(adv(5), 26), 5), 7)) - rank(decay_linear(ts_rank(ts_argmin(correlation(rank(open), rank(adv(15)), 21), 9), 7), 8))"),
    dict(name="alpha099", family="volume",
         formula="-1 * (rank(correlation(ts_sum((high + low) / 2, 20), ts_sum(adv(60), 20), 9)) < rank(correlation(low, volume, 6)))"),
    dict(name="alpha101", family="value",
         formula="(close - open) / ((high - low) + 0.001)"),

    # ---------------- classic academic factor signals ----------------
    dict(name="mom_12_1", family="momentum",
         formula="rank(delay(close, 21) / delay(close, 252) - 1)"),
    dict(name="mom_6_1", family="momentum",
         formula="rank(delay(close, 21) / delay(close, 126) - 1)"),
    dict(name="st_reversal_5", family="reversal",
         formula="-1 * rank(close / delay(close, 5) - 1)"),
    dict(name="st_reversal_1", family="reversal",
         formula="-1 * rank(returns)"),
    dict(name="overnight_gap", family="reversal",
         formula="-1 * rank(open / delay(close, 1) - 1)"),
    dict(name="volume_shock", family="volume",
         formula="-1 * rank(volume / adv(20))"),
    dict(name="amihud_illiq", family="microstructure",
         formula="rank(abs(returns) / (volume * close + 1))"),
    dict(name="low_vol", family="volatility",
         formula="-1 * rank(stddev(returns, 20))"),
    dict(name="vol_change", family="volatility",
         formula="-1 * rank(stddev(returns, 5) / stddev(returns, 60))"),
    dict(name="range_compression", family="volatility",
         formula="-1 * rank((high - low) / close)"),
    dict(name="prox_52w_high", family="momentum",
         formula="rank(close / ts_max(high, 252))"),
    dict(name="trend_strength", family="momentum",
         formula="rank(correlation(close, ts_rank(close, 60), 20))"),
    dict(name="close_loc_in_range", family="reversal",
         formula="-1 * rank(((close - low) - (high - close)) / (high - low + 0.001))"),
    dict(name="vwap_premium", family="value",
         formula="rank(vwap - close)"),
    dict(name="dollar_vol_trend", family="volume",
         formula="rank(delta(volume * close, 5))"),
    dict(name="accel", family="momentum",
         formula="rank(delta(delta(close, 5), 5))"),
    dict(name="vol_price_corr", family="volume",
         formula="-1 * correlation(rank(close), rank(volume), 20)"),
    dict(name="high_minus_low_mom", family="momentum",
         formula="rank((close - delay(close, 10)) / (ts_max(high, 10) - ts_min(low, 10) + 0.001))"),
]
